"""Add project_users many-to-many

Revision ID: 24263e951fcd
Revises: 71de014a9c93
Create Date: 2025-06-04 19:48:06.574186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24263e951fcd'
down_revision = '71de014a9c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_users')
    # ### end Alembic commands ###
